version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: harvesthub_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: harvesthub_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: always
    volumes:
      - ./firebase-service-account.json:/app/firebase-service-account.json:ro
      - ./web_dashboard:/app/web_dashboard:ro

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: harvesthub_scraper
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: always
    volumes:
      - ./firebase-service-account.json:/app/firebase-service-account.json:ro
      - ./scraper:/app


volumes:
  mongodb_data:
